### ISSUE TITLE
Can't execute with `npx run codeowners`

### ISSUE THREAD

**Issue by miketheman** [beaugunderson/codeowners#14]
I wanted to try out this tool without actively installing it into any environment, so I tried `npx run codeowners` and got this error:

```
$ npx run codeowners audit
npx: installed 5 in 1.536s
Watching /Users/<REDACTED> and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.cache ; is listed in .gitignore
Found & ignored ./.circleci ; is listed in .gitignore
...

Starting: codeowners audit
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/<REDACTED>/codeowners'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
^C
```

Using `npm install -g codeowners` worked fine, but wanted to point this out in case there's others trying out the tool.

**Comment by beaugunderson** [comment]
hmm interesting, is there a difference between npx and npx run? i’ve not
seen that incantation before

**Comment by miketheman** [comment]
@beaugunderson You're absolutely correct - there is no npx run. 🤦  Sorry for the noise, and thanks for the project!

**Comment by beaugunderson** [comment]
glad it was an easy one! [image: 😄]
